# Generated by Django 2.0.2 on 2020-09-26 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('image', models.ImageField(upload_to='studio', verbose_name='Images')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Date Uploaded')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Update')),
            ],
            options={
                'verbose_name': 'Text',
                'verbose_name_plural': 'Texts',
                'ordering': ['-created'],
            },
        ),
    ]
